import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar是仅限于Doc的概念，Blog是Docusaurus的另一个概念。
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // basicSidebar: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
  // extraSidebar: [{type: 'autogenerated', dirName: 'tutorial-extras'}],

  // But you can create a sidebar manually
  mainSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
